name: Check for Broken Links

on:
  push:
    branches:
      - main  # change to your default branch if different
  schedule:
    - cron: '0 0 * * *'  # runs daily at 00:00 UTC

jobs:
  link-check:
    name: Run Lychee link checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
